/**
 *
 */
package com.dealmacha.constants;

/**
 * @author Jay
 *
 */
public interface CmsDivisionNames {
	String MAIN_BANNER = "MAINBANNERSECTION";
	String FOUR_GRID_PROMOTION = "FOURGRIDPROMOTIONPAGESECTION";
	String FIRST_PAGE_LEFT_SIDE = "FIRSTPAGELEFTSIDESECTION";
	String FIRST_PAGE_RIGHT_SIDE = "FIRSTPAGERIGHTSIDESECTION";
	String FIRST_PROMOTION_BANNER_SECTION = "FIRSTPROMOTIONPAGESECTION";
	String SECOND_PROMOTION_BANNER_SECTION = "SECONDPROMOTIONPAGESECTION";
	String SECOND_PAGE_SECTION = "SECONDPAGESECTION";
	String THIRD_PAGE_SECTION = "THIRDPAGESECTION";
	String FOURTH_PAGE_SECTION = "FOURTHPAGESECTION";
	String TOP_HEADER_TITLE_SECTION = "TOPHEADERTITLESECTION";
	String LOGIN_PAGE_SLIDER_SECTION = "LOGINPAGESLIDERSECTION";
	String REGISTRATION_PAGE_SLIDER_SECTION = "REGISTRATIONPAGESLIDERSECTION";
	String NEWS_UPDATE_TESTIMONIAL_SECTION = "NEWSUPDATETESTIMONIALSECTION";
	
}
