package com.dealmacha.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.*;

/**
 * ClickTransaction generated by hbm2java
 */
@Entity
@Table(name = "click_transaction", catalog = "dealmacha_app")
public class ClickTransaction extends AbstractDomain implements java.io.Serializable {

    private Users users;
    private Merchant merchant;
    private Date createdDate;
    private String status;
    private String urlClicked;
    private String clickedSource;
    private String orderStatus;
    private String clickedTarget;
    private String clickedTargetId;

    public ClickTransaction() {
    }

    public ClickTransaction(final Users users, final Merchant merchant, final Date createdDate, final String status,
            final String urlClicked, final String clickedSource, final String orderStatus, final String clickedTarget,
            final String clickedTargetId) {

        this.users = users;
        this.merchant = merchant;
        this.createdDate = createdDate;
        this.status = status;
        this.urlClicked = urlClicked;
        this.clickedSource = clickedSource;
        this.orderStatus = orderStatus;
        this.clickedTarget = clickedTarget;
        this.clickedTargetId = clickedTargetId;
    }

    @Column(name = "clicked_source", nullable = false, length = 45)
    public String getClickedSource() {
        return clickedSource;
    }

    @Column(name = "clicked_target", nullable = false, length = 45)
    public String getClickedTarget() {
        return clickedTarget;
    }

    @Column(name = "clicked_target_id", nullable = false, length = 45)
    public String getClickedTargetId() {
        return clickedTargetId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_date", nullable = false, length = 19)
    public Date getCreatedDate() {
        return createdDate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "merchant_id", nullable = false)
    public Merchant getMerchant() {
        return merchant;
    }

    @Column(name = "order_status", nullable = false, length = 45)
    public String getOrderStatus() {
        return orderStatus;
    }

    @Column(name = "status", nullable = false, length = 45)
    public String getStatus() {
        return status;
    }

    @Column(name = "url_clicked", nullable = false, length = 45)
    public String getUrlClicked() {
        return urlClicked;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "users_id", nullable = false)
    public Users getUsers() {
        return users;
    }

    public void setClickedSource(final String clickedSource) {
        this.clickedSource = clickedSource;
    }

    public void setClickedTarget(final String clickedTarget) {
        this.clickedTarget = clickedTarget;
    }

    public void setClickedTargetId(final String clickedTargetId) {
        this.clickedTargetId = clickedTargetId;
    }

    public void setCreatedDate(final Date createdDate) {
        this.createdDate = createdDate;
    }

    public void setMerchant(final Merchant merchant) {
        this.merchant = merchant;
    }

    public void setOrderStatus(final String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public void setStatus(final String status) {
        this.status = status;
    }

    public void setUrlClicked(final String urlClicked) {
        this.urlClicked = urlClicked;
    }

    public void setUsers(final Users users) {
        this.users = users;
    }

}
