package com.dealmacha.domain;

// Generated 26 May, 2016 10:19:10 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * CmsBlock generated by hbm2java
 */
@Entity
@Table(name = "cms_block", catalog = "dealmacha_app")
public class CmsBlock extends AbstractDomain implements java.io.Serializable {

    private CmsSection cmsSection;
    private String blockTitle;
    private String blockName;
    private String blockPostsMin;
    private String blockPostsMax;

    private String blockStyle;

    private Integer orderOfPlace;

    private Integer postsImageWidth;

    private Integer postsImageHeight;
    private Set<CmsPosts> cmsPostses = new HashSet<CmsPosts>(0);

    public CmsBlock() {
    }

    public CmsBlock(final String id, final CmsSection cmsSection) {
        this.id = id;
        this.cmsSection = cmsSection;
    }

    public CmsBlock(final String id, final CmsSection cmsSection, final String blockTitle, final String blockName,
            final String blockPostsMin, final String blockPostsMax, final String blockStyle, final Integer orderOfPlace,
            final Set<CmsPosts> cmsPostses, final Integer postsImageWidth, final Integer postsImageHeight) {
        this.id = id;
        this.cmsSection = cmsSection;
        this.blockTitle = blockTitle;
        this.blockName = blockName;
        this.blockPostsMin = blockPostsMin;
        this.blockPostsMax = blockPostsMax;
        this.blockStyle = blockStyle;
        this.orderOfPlace = orderOfPlace;
        this.cmsPostses = cmsPostses;
        this.postsImageWidth = postsImageWidth;
        this.postsImageHeight = postsImageHeight;
    }

    @Column(name = "block_name", length = 100)
    public String getBlockName() {
        return blockName;
    }

    @Column(name = "block_posts_max", length = 45)
    public String getBlockPostsMax() {
        return blockPostsMax;
    }

    @Column(name = "block_posts_min", length = 45)
    public String getBlockPostsMin() {
        return blockPostsMin;
    }

    @Column(name = "block_style", length = 45)
    public String getBlockStyle() {
        return blockStyle;
    }

    @Column(name = "block_title", length = 100)
    public String getBlockTitle() {
        return blockTitle;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cmsBlock")
    @OrderBy("order_of_place ASC")
    public Set<CmsPosts> getCmsPostses() {
        return cmsPostses;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cms_section_id", nullable = false)
    public CmsSection getCmsSection() {
        return cmsSection;
    }

    @Column(name = "order_of_place")
    public Integer getOrderOfPlace() {
        return orderOfPlace;
    }

    @Column(name = "posts_image_height")
    public Integer getPostsImageHeight() {
        return postsImageHeight;
    }

    @Column(name = "posts_image_width")
    public Integer getPostsImageWidth() {
        return postsImageWidth;
    }

    public void setBlockName(final String blockName) {
        this.blockName = blockName;
    }

    public void setBlockPostsMax(final String blockPostsMax) {
        this.blockPostsMax = blockPostsMax;
    }

    public void setBlockPostsMin(final String blockPostsMin) {
        this.blockPostsMin = blockPostsMin;
    }

    public void setBlockStyle(final String blockStyle) {
        this.blockStyle = blockStyle;
    }

    public void setBlockTitle(final String blockTitle) {
        this.blockTitle = blockTitle;
    }

    public void setCmsPostses(final Set<CmsPosts> cmsPostses) {
        this.cmsPostses = cmsPostses;
    }

    public void setCmsSection(final CmsSection cmsSection) {
        this.cmsSection = cmsSection;
    }

    public void setOrderOfPlace(final Integer orderOfPlace) {
        this.orderOfPlace = orderOfPlace;
    }

    public void setPostsImageHeight(final Integer postsImageHeight) {
        this.postsImageHeight = postsImageHeight;
    }

    public void setPostsImageWidth(final Integer postsImageWidth) {
        this.postsImageWidth = postsImageWidth;
    }

}
