package com.dealmacha.domain;

// Generated 26 May, 2016 10:19:10 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * CmsSection generated by hbm2java
 */
@Entity
@Table(name = "cms_section", catalog = "dealmacha_app")
public class CmsSection extends AbstractDomain implements java.io.Serializable {

    private String sectionTitle;
    private String sectionName;
    private Set<CmsBlock> cmsBlocks = new HashSet<CmsBlock>(0);

    public CmsSection() {
    }

    public CmsSection(final String id) {
        this.id = id;
    }

    public CmsSection(final String id, final String sectionTitle, final String sectionName, final Set<CmsBlock> cmsBlocks) {
        this.id = id;
        this.sectionTitle = sectionTitle;
        this.sectionName = sectionName;
        this.cmsBlocks = cmsBlocks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "cmsSection")
    @OrderBy("order_of_place ASC")
    public Set<CmsBlock> getCmsBlocks() {
        return cmsBlocks;
    }

    @Column(name = "section_name", length = 100)
    public String getSectionName() {
        return sectionName;
    }

    @Column(name = "section_title", length = 100)
    public String getSectionTitle() {
        return sectionTitle;
    }

    public void setCmsBlocks(final Set<CmsBlock> cmsBlocks) {
        this.cmsBlocks = cmsBlocks;
    }

    public void setSectionName(final String sectionName) {
        this.sectionName = sectionName;
    }

    public void setSectionTitle(final String sectionTitle) {
        this.sectionTitle = sectionTitle;
    }

}
