package com.dealmacha.domain;

// Generated 7 May, 2016 4:24:03 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

import org.springframework.context.annotation.PropertySource;

/**
 * Merchant generated by hbm2java
 */
@Entity
@Table(name = "merchant", catalog = "dealmacha_app")
@PropertySource("classpath:application.properties")
public class Merchant extends AbstractDomain implements java.io.Serializable {
    /*@Value("${imageUrl}")*/

    private String affiliateId;
    private String merchantToken;
    private String merchantName;
    private String merchantImage;
    private String description;
    private String url;
    private String affiliateKey;
    private Set<ClickTransaction> clickTransactions = new HashSet<ClickTransaction>(0);
    private Set<MerchantCategory> merchantCategory = new HashSet<MerchantCategory>(0);
    private Set<Transaction> transaction = new HashSet<Transaction>(0);

    public Merchant() {
    }

    public Merchant(final String affiliateId, final String url, final String description, final String merchantToken,
            final String merchantName, final String merchantImage,final String affiliateKey) {
        this.affiliateId = affiliateId;
        this.url = url;
        this.affiliateId=affiliateId;
        this.merchantToken = merchantToken;
        this.merchantName = merchantName;
        this.merchantImage = merchantImage;
        this.description = description;
    }

    public Merchant(final String affiliateId, final String url, final String merchantToken, final String description,
            final String merchantName, final String merchantImage,final String affiliateKey, final Set<ClickTransaction> clickTransactions,
            final Set<MerchantCategory> merchantCategory, final Set<Transaction> transaction) {
        this.affiliateId = affiliateId;
        this.description = description;
        this.url = url;
        this.affiliateId=affiliateId;
        this.merchantToken = merchantToken;
        this.merchantName = merchantName;
        this.merchantImage = merchantImage;
        this.clickTransactions = clickTransactions;
        this.merchantCategory = merchantCategory;
        this.transaction = transaction;
    }

    @Column(name = "affiliate_id", nullable = false, length = 100)
    public String getAffiliateId() {
        return affiliateId;
    }
    @Column(name = "affiliate_key", nullable = false, length = 100)
    public String getAffiliateKey() {
        return affiliateKey;
    }
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
    public Set<ClickTransaction> getClickTransactions() {
        return clickTransactions;
    }

    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
    public Set<MerchantCategory> getMerchantCategory() {
        return merchantCategory;
    }

    @Column(name = "merchant_image", nullable = false, length = 100)
    public String getMerchantImage() {
        return merchantImage;
    }

    @Column(name = "merchant_name", nullable = false, length = 45)
    public String getMerchantName() {
        return merchantName;
    }

    @Column(name = "merchant_token", nullable = false, length = 100)
    public String getMerchantToken() {
        return merchantToken;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "merchant")
    public Set<Transaction> getTransaction() {
        return transaction;
    }

    @Column(name = "url", nullable = false, length = 100)
    public String getUrl() {
        return url;
    }

    public void setAffiliateId(final String affiliateId) {
        this.affiliateId = affiliateId;
    }
    public void setAffiliateKey(final String affiliateKey) {
        this.affiliateKey = affiliateKey;
    }
    public void setClickTransactions(final Set<ClickTransaction> clickTransactions) {
        this.clickTransactions = clickTransactions;
    }

    public void setDescription(final String description) {
        this.description = description;
    }

    public void setMerchantCategory(final Set<MerchantCategory> merchantCategory) {
        this.merchantCategory = merchantCategory;
    }

    public void setMerchantImage(final String merchantImage) {
        this.merchantImage = merchantImage;
    }

    public void setMerchantName(final String merchantName) {
        this.merchantName = merchantName;
    }

    public void setMerchantToken(final String merchantToken) {
        this.merchantToken = merchantToken;
    }

    public void setTransaction(final Set<Transaction> transaction) {
        this.transaction = transaction;
    }

    public void setUrl(final String url) {
        this.url = url;
    }
}
