package com.dealmacha.domain;
// Generated Jul 12, 2016 5:47:00 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Requests generated by hbm2java
 */
@Entity
@Table(name = "requests", catalog = "dealmacha_app")
public class Requests extends AbstractDomain implements java.io.Serializable {

	private RequestTypes requestTypes;
	private Users users;
	private String requestType;
	private BigDecimal amount;
	private String requestComments;
	private String requestStatus;
	private Date createdDate;
	private Date modifiedDate;

	public Requests() {
	}

	public Requests(String id, Users users, BigDecimal amount, String requestType, String requestStatus,
			Date createdDate) {
		this.id = id;
		this.users = users;
		this.requestType = requestType;
		this.amount = amount;
		this.requestStatus = requestStatus;
		this.createdDate = createdDate;
	}

	public Requests(String id, RequestTypes requestTypes, Users users, String requestType, String requestComments,
			String requestStatus, Date createdDate, Date modifiedDate) {
		this.id = id;
		this.requestTypes = requestTypes;
		this.users = users;
		this.requestType = requestType;
		this.requestComments = requestComments;
		this.requestStatus = requestStatus;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "request_types_id")
	public RequestTypes getRequestTypes() {
		return this.requestTypes;
	}

	public void setRequestTypes(RequestTypes requestTypes) {
		this.requestTypes = requestTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "request_type", nullable = false, length = 500)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@Column(name = "request_comments", length = 500)
	public String getRequestComments() {
		return this.requestComments;
	}

	public void setRequestComments(String requestComments) {
		this.requestComments = requestComments;
	}

	@Column(name = "request_status", nullable = false, length = 45)
	public String getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 19)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

}
