package com.dealmacha.domain;
// Generated Jul 12, 2016 5:47:00 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequestTypes generated by hbm2java
 */
@Entity
@Table(name = "request_types", catalog = "dealmacha_app")
public class RequestTypes extends AbstractDomain implements java.io.Serializable {

	private String requestType;
	private Date createdDate;
	private String status;
	private String requestDescription;
	private Set<Requests> requestses = new HashSet<Requests>(0);
	private Set<RequestTypeAttributes> requestTypeAttributeses = new HashSet<RequestTypeAttributes>(0);
	public RequestTypes() {
	}

	public RequestTypes(String id, String requestType, Date createdDate) {
		this.id = id;
		this.requestType = requestType;
		this.createdDate = createdDate;
	}

	public RequestTypes(String id, String requestType, Date createdDate, String status, String requestDescription, Set<Requests> requestses) {
		this.id = id;
		this.requestType = requestType;
		this.createdDate = createdDate;
		this.status = status;
		this.requestDescription = requestDescription;
		this.requestses = requestses;
	}


	@Column(name = "request_type", nullable = false, length = 45)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}


	@Column(name = "request_description", length = 500)
	public String getRequestDescription() {
		return this.requestDescription;
	}

	public void setRequestDescription(String requestDescription) {
		this.requestDescription = requestDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public Set<Requests> getRequestses() {
		return this.requestses;
	}

	public void setRequestses(Set<Requests> requestses) {
		this.requestses = requestses;
	}
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "requestTypes")
	public Set<RequestTypeAttributes> getRequestTypeAttributeses() {
		return requestTypeAttributeses;
	}

	public void setRequestTypeAttributeses(Set<RequestTypeAttributes> requestTypeAttributeses) {
		this.requestTypeAttributeses = requestTypeAttributeses;
	}

}
